spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tour
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  signerKey: "KOX/fR5t6kwik5fNnaoNCEe9tJFxcIqAHxUP82D1Pzy/YflIqgBnN26FkUd9kbPz"
  valid-duration: 3600
  refreshable-duration: 36000